CC = cc

CFLAGS = -Wall -Wextra -Werror

AR =ar rcs

NAME = libft.a

HEADER = libft.h

SRC = ft_isalnum.c ft_isdigit.c ft_strlen.c ft_isalpha.c	ft_isprint.c ft_bzero.c	ft_isascii.c ft_memset.c ft_memcpy.c ft_memmove.c \
	 ft_strlcpy.c ft_strlcat.c ft_calloc.c ft_tolower.c ft_toupper.c ft_strchr.c ft_strrchr.c ft_atoi.c ft_strncmp.c ft_memchr.c ft_memcmp.c \
	 ft_strnstr.c ft_strdup.c ft_substr.c ft_strjoin.c ft_strnstr.c ft_split.c ft_itoa.c ft_strmapi.c ft_strtrim.c ft_striteri.c ft_putchar_fd.c \
	 ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c

BONUS = ft_lstadd_back_bonus.c ft_lstadd_front_bonus.c ft_lstclear_bonus.c ft_lstdelone_bonus.c ft_lstiter_bonus.c ft_lstlast_bonus.c ft_lstnew_bonus.c ft_lstsize_bonus.c ft_lstmap_bonus.c 

OBJ = ${SRC:.c=.o}

BOBJ = ${BONUS:.c=.o}

all: ${NAME}

${NAME}: ${OBJ} 
	

bonus :${OBJ} ${BOBJ} 


%.o: %.c ${HEADER} 
	${CC} ${CFLAGS} -c $< -o $@ 
	${AR} ${NAME} $@

clean:
	rm -f ${OBJ} ${BOBJ}

fclean: clean
	rm -f $(NAME)
 
re: fclean all

